### ISSUE TITLE
您好，能给个联系方式么，关于这个MFC的GDI函数绘图，我有问题想要和你请教下谢谢了。

### ISSUE THREAD

**Issue by Qianzujin** [huihut/GraphicsExercise3D#1]
您好，能给个联系方式么，关于这个MFC的GDI函数绘图，我有问题想要和你请教下谢谢了。

**Comment by huihut** [comment]
发邮件给我就可以了：<huihut@outlook.com>

**Comment by Qianzujin** [comment]
好的，谢谢了

> 发邮件给我就可以了：[huihut@outlook.com](mailto:huihut@outlook.com)

好的，谢谢了，请问你这边有做过关于坐标系内绘图的项目么，坐标系和图形函数的对应关系是怎么确定的，我总是弄不大好这个。

**Comment by huihut** [comment]
没有，这个仓库的东西只是上图形学课的时候做的练习。

关于你说的 `坐标系和图形函数的对应关系`，这个是指 [三维转二维的推导](https://github.com/huihut/GraphicsExercise3D#%E4%B8%89%E7%BB%B4%E8%BD%AC%E4%BA%8C%E7%BB%B4%E7%9A%84%E6%8E%A8%E5%AF%BC) 还是什么？你的疑惑是什么？

**Comment by Qianzujin** [comment]
就是说我用您这个二维的坐标系想画一个x的平方的图像就是不知道怎么弄。。。

**Comment by Qianzujin** [comment]
还有您学习的课程，有教材嘛。。我也想看一下。。

**Comment by huihut** [comment]
二维的用这个：https://github.com/huihut/GraphicsExercise2D

emmm，教材忘记是什么了，都没怎么看。

**Comment by Qianzujin** [comment]
emmm，其实我看了那个二维的，然后不是很懂，，就在函数那里我写了个y等于x的平方，然后画图就显示的很奇怪。。。
